
Class = ['RIGHT_CFA', 'RIGHT_SFA', 'RIGHT_DFA', 'RIGHT_POPA', 'RIGHT_ATA', 'RIGHT_PTA', 'RIGHT_PA', 'RIGHT_DORSALIS',
         'LEFT_CFA', 'LEFT_SFA', 'LEFT_DFA', 'LEFT_POPA', 'LEFT_ATA', 'LEFT_PTA', 'LEFT_PA', 'LEFT_DORSALIS']
         
class_name ={
### Right
0: 'RIGHT_CFA_LONG',
1: 'RIGHT_SFA_LONG',
2: 'RIGHT_DFA_LONG',
3: 'RIGHT_POPA_LONG',
4: 'RIGHT_ATA_LONG',
5: 'RIGHT_PTA_LONG',
6: 'RIGHT_PA_LONG',
7: 'RIGHT_DORSALIS_LONG',

8: 'RIGHT_CFA_SHORT',
9: 'RIGHT_SFA_SHORT',
10: 'RIGHT_DFA_SHORT',
11: 'RIGHT_POPA_SHORT',
12: 'RIGHT_ATA_SHORT',
13: 'RIGHT_PTA_SHORT',
14: 'RIGHT_PA_SHORT',
15: 'RIGHT_DORSALIS_SHORT',

### Left
16: 'LEFT_CFA_LONG',
17: 'LEFT_SFA_LONG',
18: 'LEFT_DFA_LONG',
19: 'LEFT_POPA_LONG',
20: 'LEFT_ATA_LONG',
21: 'LEFT_PTA_LONG',
22: 'LEFT_PA_LONG',
23: 'LEFT_DORSALIS_LONG',

24: 'LEFT_CFA_SHORT',
25: 'LEFT_SFA_SHORT',
26: 'LEFT_DFA_SHORT',
27: 'LEFT_POPA_SHORT',
28: 'LEFT_ATA_SHORT',
29: 'LEFT_PTA_SHORT',
30: 'LEFT_PA_SHORT',
31: 'LEFT_DORSALIS_SHORT'
}